### ISSUE TITLE
Save function

### ISSUE THREAD

**Issue by xhajnal** [sybila/pithya-gui#32]
Save function doesn't work:
- Editor.saveModel
- Editor.saveProperties
- Result.saveResults

**Comment by martindemko** [comment]
It is working but only from browser, which is fine, because standard user wouldn't probably have installed RStudio. There is only one issue needs to be resolved. If the button 'save model' should save the current state of input-model-text-area or a model stored inside and used currently as the observed experiment. I will appreciate some opinions.

**Comment by martindemko** [comment]
DONE - please for check
